name: Release latest agent-runner

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get variables
        id: vars
        run: |
          echo "reponame=${GITHUB_REPOSITORY,,}" >>${GITHUB_OUTPUT}
      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./infrastructure/images/gh-runner
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.vars.outputs.reponame }}:latest
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}